[2023-11-22T09:59:24.671+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summery.load_episode manual__2023-11-22T04:14:17.514708+00:00 [queued]>
[2023-11-22T09:59:24.677+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summery.load_episode manual__2023-11-22T04:14:17.514708+00:00 [queued]>
[2023-11-22T09:59:24.678+0545] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T09:59:24.686+0545] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_episode> on 2023-11-22 04:14:17.514708+00:00
[2023-11-22T09:59:24.690+0545] {standard_task_runner.py:57} INFO - Started process 237452 to run task
[2023-11-22T09:59:24.692+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'podcast_summery', 'load_episode', 'manual__2023-11-22T04:14:17.514708+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summery.py', '--cfg-path', '/tmp/tmp6zif525l']
[2023-11-22T09:59:24.694+0545] {standard_task_runner.py:85} INFO - Job 134: Subtask load_episode
[2023-11-22T09:59:24.714+0545] {task_command.py:416} INFO - Running <TaskInstance: podcast_summery.load_episode manual__2023-11-22T04:14:17.514708+00:00 [running]> on host dwarka.dwarka
[2023-11-22T09:59:24.759+0545] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='podcast_summery' AIRFLOW_CTX_TASK_ID='load_episode' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T04:14:17.514708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T04:14:17.514708+00:00'
[2023-11-22T09:59:24.765+0545] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/airflow/dags/podcast_summery.py", line 48, in load_episode
    stored=hook.get_pandas_df("SELECT * FROM episodes;")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 218, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 37, in get_conn
    sqlalchemy_uri = self.get_uri()
                     ^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 47, in get_uri
    airflow_conn = self.get_connection(conn_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `episodes` isn't defined
[2023-11-22T09:59:24.770+0545] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summery, task_id=load_episode, execution_date=20231122T041417, start_date=20231122T041424, end_date=20231122T041424
[2023-11-22T09:59:24.777+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 134 for task load_episode (The conn_id `episodes` isn't defined; 237452)
[2023-11-22T09:59:24.784+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T09:59:24.791+0545] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
