[2023-11-20T12:32:17.434+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summery.download_episodes manual__2023-11-20T06:47:08.011920+00:00 [queued]>
[2023-11-20T12:32:17.439+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summery.download_episodes manual__2023-11-20T06:47:08.011920+00:00 [queued]>
[2023-11-20T12:32:17.439+0545] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-20T12:32:17.448+0545] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): download_episodes> on 2023-11-20 06:47:08.011920+00:00
[2023-11-20T12:32:17.452+0545] {standard_task_runner.py:57} INFO - Started process 129410 to run task
[2023-11-20T12:32:17.454+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'podcast_summery', 'download_episodes', 'manual__2023-11-20T06:47:08.011920+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summery.py', '--cfg-path', '/tmp/tmpy5fnrq6a']
[2023-11-20T12:32:17.455+0545] {standard_task_runner.py:85} INFO - Job 34: Subtask download_episodes
[2023-11-20T12:32:17.476+0545] {task_command.py:416} INFO - Running <TaskInstance: podcast_summery.download_episodes manual__2023-11-20T06:47:08.011920+00:00 [running]> on host dwarka.dwarka
[2023-11-20T12:32:17.523+0545] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='podcast_summery' AIRFLOW_CTX_TASK_ID='download_episodes' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T06:47:08.011920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-20T06:47:08.011920+00:00'
[2023-11-20T12:32:17.525+0545] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/airflow/dags/podcast_summery.py", line 60, in download_episodes
    audio_path=os.path.join("episodes", filename)
               ^^
NameError: name 'os' is not defined
[2023-11-20T12:32:17.529+0545] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summery, task_id=download_episodes, execution_date=20231120T064708, start_date=20231120T064717, end_date=20231120T064717
[2023-11-20T12:32:17.536+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task download_episodes (name 'os' is not defined; 129410)
[2023-11-20T12:32:17.546+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T12:32:17.554+0545] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
